version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Password1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Password1
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.172.28.128.30.xip.io`)"
      - "traefik.docker.network=vagrant_traefik-net"
      - "traefik.enable=true"
    logging:
      driver: "fluentd"
      options:
       fluentd-address: "tcp://127.0.0.1:24224"
       fluentd-async-connect: "true"
       tag: devel.kris

volumes:
  db_data: {}
